Alexander melentyev/unit tests
zhashkevych/creatly-backend pull request #59
Opened 2021-05-18 15:46 UTC by alexander-melentyev

2021-05-18 17:11 UTC, koind commented on internal/delivery/http/handler_test.go
> +func TestNewHandler_Init(t *testing.T) {
(предложение, не критично) Добавить еще один тест на проверку лимитера. То есть, при отправке множественных запросов на `/ping` срабатывает лимитер и в ответ возвращается код со статусом `http.StatusTooManyRequests`

2021-05-18 17:14 UTC, alexander-melentyev commented on internal/delivery/http/handler_test.go
> +func TestNewHandler_Init(t *testing.T) {
Я про это думал тоже, но решил покрыть вначале все базовые кейсы

2021-05-18 17:15 UTC, koind commented on internal/delivery/http/handler_test.go
> +func TestNewHandler_Init(t *testing.T) {
Ок)

2021-05-18 17:58 UTC, koind requested changes

2021-05-18 17:58 UTC, koind commented on internal/service/admins_test.go
> +	adminMock := mock_repository.NewMockAdmins(mockCtl)
Предлагаю переименовать `adminMock` на `adminRepo`, также и `schoolsMock` на `schoolsRepo` во всем тесте. Читаемость повышается.

2021-05-18 17:58 UTC, koind commented on internal/service/admins_test.go
> +	adminMock.EXPECT().GetByCredentials(ctx, gomock.Any(), gomock.Any(), gomock.Any())
На счет моков репозиториев. Предлагаю сделать memory репозитории, которые будут сохранят данные в памяти и доставать соотвественно. Вот к примеру - https://github.com/koind/cacher/blob/main/internal/storage/memory/%D1%81ache.go

Также данные похожие на реальные передавать желательно так, как больше шансов отловить баг при изменении. Т.е заполнять структуры которые передаем в инпут и также сравнивать с заполненным ожидаемыми значениями.

В остальных тестах также.

2021-05-18 18:01 UTC, alexander-melentyev commented on internal/service/admins_test.go
> +	adminMock.EXPECT().GetByCredentials(ctx, gomock.Any(), gomock.Any(), gomock.Any())
Это уже будут интеграционные тесты. Для юнит тестов достаточно моков

2021-05-18 18:04 UTC, alexander-melentyev commented on internal/service/admins_test.go
> +	adminMock.EXPECT().GetByCredentials(ctx, gomock.Any(), gomock.Any(), gomock.Any())
Для интеграционных тестов даже выделили директорию https://github.com/zhashkevych/creatly-backend/tree/main/tests - там как раз подключается монга реальная

2021-05-19 05:52 UTC, alexander-melentyev commented on internal/service/admins_test.go
> +	adminMock := mock_repository.NewMockAdmins(mockCtl)
Я не против. Давай еще подождем - что думают другие

2021-05-19 06:14 UTC, zhashkevych commented on internal/service/admins_test.go
> +	adminMock := mock_repository.NewMockAdmins(mockCtl)
плюсую

2021-05-19 06:16 UTC, zhashkevych commented on internal/service/admins_test.go
> +	adminMock.EXPECT().GetByCredentials(ctx, gomock.Any(), gomock.Any(), gomock.Any())
@koind не совсем согласен, я предлагаю продолжить использовать моки, для которых мы предопределяем поведение.

Однако да, вместо `gomock.Any()` стоит использовать разные варианты реальных данных

2021-05-19 06:18 UTC, alexander-melentyev commented on internal/service/admins_test.go
> +	adminMock.EXPECT().GetByCredentials(ctx, gomock.Any(), gomock.Any(), gomock.Any())
Окей, предлагаю тогда сделать негласным правилом использовать gomock.Any() только в тех случаях, когда данные мутируются внутри функции

2021-05-19 06:19 UTC, zhashkevych commented
В целом по пулл реквесту хочу сказать что на данном этапе это тесты ради тестов которые ничего не проверяют, они не несут практической пользы. Если посмотреть на тесты в хендлерах, то там для каждого метода есть `testTable`, в котором собранно куча кейсов с валидными и невалидными входящими значениями, а также кейсами когда сервис отдает ошибку.

Сейчас для всех входящих данных используется `gomock.Any()`, нужно же проверять что методы вызываются как раз таки с нужными значениями, которые мы получили на входе в метод или сгенирировали внутри метода.

Для каждого сервиса стоит описать свой `testTable` по аналогии с хендлерами, который будет проверять все возможные позитивные и негативные сценарии

2021-05-19 06:21 UTC, zhashkevych reviewed
В целом по пулл реквесту хочу сказать что на данном этапе это тесты ради тестов которые ничего не проверяют, они не несут практической пользы. Если посмотреть на тесты в хендлерах, то там для каждого метода есть `testTable`, в котором собранно куча кейсов с валидными и невалидными входящими значениями, а также кейсами когда сервис отдает ошибку.

Сейчас для всех входящих данных используется `gomock.Any()`, нужно же проверять что методы вызываются как раз таки с нужными значениями, которые мы получили на входе в метод или сгенирировали внутри метода.

Для каждого сервиса стоит описать свой `testTable` по аналогии с хендлерами, который будет проверять все возможные позитивные и негативные сценарии

2021-05-19 06:26 UTC, alexander-melentyev commented
@zhashkevych Тут хочу отменить, что и логики - которую бы нужно было проверять тестами особо-то и нет. В основном все сервисы - отправлять данные напрямую в слой репозиторий. Поэтому тут табличные тесты - на этом этапе по крайней мере - выглядят избыточными. Если с хендлерами понятно - там много валидации - то здесь же не особо понятно. на текущем этапе можно обойти проверкой итоговых параметров вместо gomock.Any()

2021-05-19 16:37 UTC, alexander-melentyev commented on internal/service/admins_test.go
> +	adminMock.EXPECT().GetByCredentials(ctx, gomock.Any(), gomock.Any(), gomock.Any())
Обсудили голосом, в сервисах где нет бизнес логики - делаем проверки только на ошибки и положительный сценарий

2021-05-19 16:52 UTC, merged